### PR TITLE
Diagonal approach for more aggressive vectorization added

### PR DESCRIPTION
**Pull request by Riyazul555**

### CODE REVIEW

**Comment by Riyazul555** [comment]
Hey @ashvardanian I left some part in this PR  for accessing the matrix elements and and Performing Levenshtein distance computation.....You can add them and if not let me know how to modify them ....I will do it
Thanks

**Comment by ashvardanian** [comment]
Hi @Riyazul555! Can you explain what you are trying to achieve with this?

**Comment by Riyazul555** [comment]
Well this PR is for issue #78 @ashvardanian

**Comment by ashvardanian** [comment]
Your added loop does nothing. It's not a solution to #78.

**Pull request closed without merging**
