### PR TITLE
Update release.yml clang version

### PR DESCRIPTION
**Pull request by ashbob999**
Updated the release.yml Clang version to 16, to avoid build issues.
This had got forgotten from #136 .

### CODE REVIEW

**Comment by ashvardanian** [comment]
Can you please rebase from the upstream branch? I've squashed some of the commits 🤗

**Comment by ashbob999** [comment]
> Can you please rebase from the upstream branch? I've squashed some of the commits 🤗

Doing it right now.

**Comment by ashbob999** [comment]
@ashvardanian fixed now.

**Pull request merged**
