### PR TITLE
Fix: Swift bindings

### PR DESCRIPTION
**Pull request by vmanot**

### CODE REVIEW

**Comment by ashvardanian** [comment]
Thank you for the contribution, @vmanot! Looks good! Will be waiting for your confirmation to merge 🤗

**Comment by vmanot** [comment]
@ashvardanian I think the surface API is good for now, might PR some minor tweaks later.

**Comment by ashvardanian** [comment]
@vmanot, thank you for the PR! Happy to merge, but have a couple of questions:

1. Don't we need a `throw StringZillaError.contiguousStorageUnavailable` in `extension String: StringZillaViewable`, similar to other extensions?
2. If those exceptions are thrown, how do they propagate to the user? Seems like the "find" functions will just return `nil` for a missing match. Is there a good way to test/document those behaviors?

**Comment by vmanot** [comment]
@ashvardanian pushing something for this tomorrow.

**Comment by ashvardanian** [comment]
Hi @vmanot! Can I please ask you to rebase from the development branch. I've decided to remove the `package-lock.json` from the history. It was over 7000 lines of JSON polluting the project, and I don't want every DBMS or runtime to end up pulling that noise. Thank you for understanding 🤗

**Comment by vmanot** [comment]
@ashvardanian yes of course!

**Comment by ashvardanian** [comment]
Hey @vmanot! There is now a CI job that tests Swift on both Linux and MacOS. Should help us both 🤗 

PS: There may be a bug in the binding catched by the `testFindLastCharacterNotFromSet`, which I've commented out for now.

**Review by ashvardanian — APPROVED** [review]

**Comment by ashvardanian** [comment]
Hi @vmanot! I've managed to rebase your commits onto the `main-dev`, so I'm closing this PR. Thanks for the contribution 🤗

**Pull request closed without merging**
